import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google"; // Import Space Grotesk
import "./globals.css";
import ProtectedRoute from "./protectedRoute"; // Import your client-side protection logic

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk", // Optional, for custom CSS variable
  weight: ["300", "400", "500", "600", "700"], // Choose the weight range
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        {/* Wrap content with ProtectedRoute for client-side authentication */}
        <ProtectedRoute>
          {children}
        </ProtectedRoute>
      </body>
    </html>
  );
}